name: test app

on:
  push:
    branches: '*'

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Run compiler check
        run: yarn tsc
      - name: Run linter
        run: yarn lint:check
